apiVersion: v1
kind: Service
metadata:
  name: aksdemo-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: aksdemo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: aksdemo