# Default values for aspnetcore-aad-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

aadPodIdBinding: # aad pod identity binding

image:
  repository: ghcr.io/chunliu/aspnetcore-aad
  pullPolicy: IfNotPresent
  tag: "v0.5.5"

service:
  type: ClusterIP
  port: 80

ingress:
  canary: false
  weight: 0
  class: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-issuer
  hosts:
    - host: # yoursite.yourdomain.com
      paths:
        - /
  tls: 
    - secretName: frontend-tls
      hosts:
        # - yoursite.yourdomain.com

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  aadDomain: # qualified.domain.name
  aadClientId: # Client Id
  aadTenantId: # Tenant Id
  keyVaultUri: # Azure key vault Uri
  userAssignedIdentityClientId: # User assigned identity, has permission to the key vault
  secretName: # The secret name
  hostingEnv: # The hosting environment, e.g. Dev, Prod etc.
