# Default values for aspnetcore-aad-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/chunliu/aspnetcore-aad
  pullPolicy: IfNotPresent
  tag: "v0.2.0"

service:
  type: ClusterIP
  port: 80

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/issuer: letsencrypt-issuer
  hosts:
    - host: # yoursite.yourdomain.com
      paths:
        - /
  tls: 
    - secretName: # chart-example-tls
      hosts:
        # - yoursite.yourdomain.com

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  aadDomain: # qualified.domain.name
  aadClientId: # Client Id
  aadTenantId: # Tenant Id
  aksCluster: akscluster1 # The name of the aks cluster
